### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by venky9885** [jspw/Codeforces-App#2]
Add backend support firebase it will be very much nice

**Comment by jspw** [comment]
Can you explain more ? I didn't get it.
For your information i am not running backend as i am using a api made by Codeforces.com.

**Comment by venky9885** [comment]
If you send data from app it will be stored in firebase database and after fetch you'll get it, this will be helpful for using our own information in app, by adding bacend support this project be fullfill completely ❗

**Comment by jspw** [comment]
Why do i need to send data to backend? and which type of data you are talking about? you cant modify the informations of codeforces without logging in to cf.
Can you please tell me what feature you are talking about?
Have you checked the api yet?

**Comment by venky9885** [comment]
I am not talking about codeforces that is different from my view with Backend Support ❗
